import React from 'react';
import styled from 'styled-components';

const ErrorMessage = styled.div`
    width: 30%;
    margin: 10% auto;
    box-shadow: 0px 0px 1px 1px #d4d4d4;
    font-size: 1em;
    padding: 2%;
    font-weight: 400;

    & h3:nth-child(2) {
        color: gray;
        font-weight: 400;
    }

    & h3:nth-child(4) {
        color: #b8b8b8;
        font-weight: 400;
    }

    & .errorCode {
        color: #ffa600;
    }
`;

const ErrorPage = () => {
    return (
        <ErrorMessage>
            <h3 className="errorCode">404</h3>
            <h3>Page Not Found</h3>
            <p>The specified file was not found on this website. Please check the URL for mistakes and try again.</p>
            <h3>Why am I seeing this?</h3>
            <p>This page was generated by the Firebase Command-Line Interface. To modify it, edit the 404.html file in your project's configured public directory.</p>
        </ErrorMessage>
    )
}

export default ErrorPage
